micronaut:
  application:
    name: flywayDemo

datasources:
  default:
    url: "jdbc:postgresql://localhost:5432/demo?currentSchema=public"
    username: "demo"
    password: "***"
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
    schema-generate:  NONE # [ NONE | CREATE | CREATE_DROP]

# "Invalid SQL filenames" => https://github.com/flyway/flyway/issues/3430
# https://micronaut-projects.github.io/micronaut-flyway/latest/guide/#additionalConfig
flyway:
  datasources:
    default:
      enabled: true # true | false
      baseline-on-migrate: true
      validate-migration-naming: true